### ISSUE TITLE
Is there a polyfill for this?

### ISSUE THREAD

**Issue by getify** [FrankYFTang/proposal-intl-extend-timezonename#14]
I need to support Node 16.20 (which has v8 v9.4, and this feature was unfortunately added in v9.5). Is there any polyfill for it that I can still use?

**Comment by getify** [comment]
+ @FrankYFTang @ptomato

**Comment by FrankYFTang** [comment]
I do not believe any version of v8 officially support this proposal yet.

**Comment by getify** [comment]
It is definitely supported by v8 as of 9.5 (Sept 2021, so almost 2 years now). It works in my browser, and it works in Node 17. Just not Node 16 that I need to support on one of my servers.

I was under the impression that most/all such proposals (API based, not syntax) would have polyfills as part of the spec process. Is that not the case here?

**Comment by FrankYFTang** [comment]
I am sorry. I got mixed up with another proposal with similar name.

**Comment by FrankYFTang** [comment]
https://tc39.es/process-document/

Stage ... Implementation Types Expected*
1 ... Polyfills / demos
...

* This column does not indicate a requirement for advancement, but simply a general expectation.

**Comment by FrankYFTang** [comment]
this proposal was part of 2022 Edition of ECMA402. I should close down the repo. Please file issue in ecma402 from now on about this.
